# ini yang pertama kalau mau buat user ga pake --auth kalau mau run auth nya
# harus edit lagi jadi --auth di bagian mongod

version: "3.5"

services:
  mongo-unsecure:
    container_name: mongo-unsecure
    image: mongo:4.2
    ports:
      - 37027:27017
    command: mongod
    # command: mongod --auth
